/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cazzodidoccia.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0, 0, 0.05]} />
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 0, 0.58]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[0.35, 0, -1.4]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh geometry={nodes.Cube001_1.geometry} material={nodes.Cube001_1.material} />
      <mesh
        geometry={nodes.pomello.geometry}
        material={materials.pomello}
        position={[0.24, 0.95, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.03, 0.01]}
      />
      <mesh
        geometry={nodes.cerniere1.geometry}
        material={nodes.cerniere1.material}
        position={[-0.29, 0.42, 0]}
        scale={[1, 1, 0.71]}
      />
      <mesh
        geometry={nodes.cerniereadd.geometry}
        material={nodes.cerniereadd.material}
        position={[-0.29, 1.05, 0]}
        scale={[1, 1, 0.71]}
      />
      <mesh
        geometry={nodes.cerniere2.geometry}
        material={nodes.cerniere2.material}
        position={[-0.29, 1.6, 0]}
        scale={[1, 1, 0.71]}
      />
      <group position={[0.31, 0, -0.2]} scale={[1, 1, 0.64]}>
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
        <mesh geometry={nodes.Cube005_1.geometry} material={nodes.Cube005_1.material} />
      </group>
      <group position={[0.31, 1, -0.2]} scale={[1, 0.5, 0.64]}>
        <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} />
        <mesh geometry={nodes.Cube007_1.geometry} material={nodes.Cube007_1.material} />
        <mesh geometry={nodes.Cube007_2.geometry} material={nodes.Cube007_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/cazzodidoccia.gltf')
