/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/doccia1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.door_1.geometry} material={nodes.door_1.material} />
      <mesh geometry={nodes.door_2.geometry} material={nodes.door_2.material} />
      <mesh
        geometry={nodes.pomello.geometry}
        material={materials.pomello}
        position={[0.24, 0.95, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.03, 0.01]}
      />
      <mesh
        geometry={nodes.cerniere1.geometry}
        material={nodes.cerniere1.material}
        position={[-0.29, 0.42, 0]}
        scale={[1, 1, 0.71]}
      />
      <mesh
        geometry={nodes.cerniereadd.geometry}
        material={nodes.cerniereadd.material}
        position={[-0.29, 1.05, 0]}
        scale={[1, 1, 0.71]}
      />
      <mesh
        geometry={nodes.cerniere2.geometry}
        material={nodes.cerniere2.material}
        position={[-0.29, 1.6, 0]}
        scale={[1, 1, 0.71]}
      />
      <group position={[0.31, 0, -0.2]} scale={[1, 1, 0.64]}>
        <mesh geometry={nodes.panel1_1.geometry} material={nodes.panel1_1.material} />
        <mesh geometry={nodes.panel1_2.geometry} material={nodes.panel1_2.material} />
      </group>
      <group position={[0.31, 1, -0.2]} scale={[1, 0.5, 0.64]}>
        <mesh geometry={nodes.panel2_1.geometry} material={nodes.panel2_1.material} />
        <mesh geometry={nodes.panel2_2.geometry} material={nodes.panel2_2.material} />
        <mesh geometry={nodes.panel2_3.geometry} material={nodes.panel2_3.material} />
      </group>
      <mesh
        geometry={nodes.muras.geometry}
        material={nodes.muras.material}
        position={[0, 0, 0.58]}
        scale={[1, 1.29, 1]}
      />
      <mesh geometry={nodes.muro1.geometry} material={nodes.muro1.material} position={[0, 0, 0.05]} />
      <mesh
        geometry={nodes.muro2.geometry}
        material={nodes.muro2.material}
        position={[0.35, 0, -1.4]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/doccia1.gltf')
